version: '3.8'

services:
  db:
    image: postgres:15
    container_name: job_postings
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sozjavbxj
      - POSTGRES_DB=job_postings
    command:
      - postgres
      - -c listen_addresses=*
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - job_network

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=debug
      - LOG_HTML=true
      - CAPTCHA_SOLVER=none
      - TZ=UTC
    ports:
      - "8191:8191"
    networks:
      - scraper_network
    restart: unless-stopped

networks:
  job_network:
    driver: bridge

volumes:
  pgdata: