name: Playwright Test
on:
  workflow_dispatch:  # Allows manual trigger from the Actions tab
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libnss3 \
            libxss1 \
            libasound2 \
            libatk-bridge2.0-0 \
            libgbm-dev \
            libgtk-3-0 \
            libxshmfence-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pytest playwright
          playwright install chromium

      - name: Run Playwright Tests
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python -m pytest tests/test_playwright.py -v

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        if: failure() || success()
        with:
          name: playwright-test-artifacts
          path: |
            example_screenshot.png
            *.log
          retention-days: 7