name: Playwright Test
on:
  workflow_dispatch:  # Allows manual trigger from the Actions tab
  # Uncomment the following if you want to trigger on push or pull request
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  test-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install pytest playwright python-dotenv
          playwright install chromium


      - name: Debug Environment
        run: |
          echo "Python version:"
          python --version
          echo "Python path:"
          which python
          echo "Playwright version:"
          pip show playwright

      - name: Run Playwright Tests
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python -m pytest tests/
        # Note: Replace 'tests/' with the path to your Playwright test scripts