name: Playwright Test
on:
  workflow_dispatch:  # Allows manual trigger from the Actions tab
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libnss3 \
            libxss1 \
            libatk-bridge2.0-0 \
            libgbm-dev \
            libgtk-3-0 \
            libxshmfence-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pytest playwright python-dotenv
          playwright install chromium

      - name: Debug Environment
        run: |
          echo "Python version:"
          python --version
          echo "Python path:"
          which python
          echo "Playwright version:"
          pip show playwright
          echo "Checking Playwright browser installation:"
          playwright install

      - name: Run Playwright Tests
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python -m pytest /path/to/specific/test_playwright_file.py -v
        # The -k "playwright" flag runs only tests with "playwright" in their name
        # This prevents running unrelated tests in the tests/ directory

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            *.png
            *.log
          retention-days: 3