name: Test Enhanced Indeed Scraper

on:
  workflow_dispatch:
    inputs:
      category:
        description: 'Job category to test'
        required: false
        default: 'python_developer'
        type: choice
        options:
          - python_developer
          - data_engineer
          - data_scientist

jobs:
  test-enhanced-indeed-scraper:
    runs-on: ubuntu-latest
    env:
      LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
      LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
      FLARESOLVERR_URL: http://host.docker.internal:8191/v1  # Host connection for GitHub runners

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            docker-compose \
            xvfb \
            libnss3 \
            libgbm-dev \
            libgtk-3-0 \
            libxss1 \
            libatk-bridge2.0-0 \
            libx11-xcb1 \
            libxcb-dri3-0 \
            libdrm2 \
            libgbm1 \
            curl \
            dnsutils

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.actions.txt
          pip install playwright httpx
          playwright install chromium
          playwright install-deps

      - name: Start FlareSolverr Service
        run: |
          docker-compose up -d flaresolverr
          
          echo "Waiting for FlareSolverr to be ready..."
          max_attempts=10
          attempt=0
          until docker run --network host curlimages/curl -s http://host.docker.internal:8191/health | grep "ok" || [ $attempt -eq $max_attempts ]; do
            echo "Attempt $((attempt+1)) failed... retrying"
            sleep 10
            attempt=$((attempt+1))
          done
          
          if [ $attempt -eq $max_attempts ]; then
            echo "FlareSolverr failed to become ready"
            docker-compose logs
            exit 1
          fi
          
          echo "FlareSolverr is ready"

      - name: Debug Network Configuration
        run: |
          echo "Network interfaces:"
          ip addr

          echo "Docker networks:"
          docker network ls

          echo "Inspecting Docker network 'job_network':"
          docker network inspect job_network || true

          echo "Current Docker containers:"
          docker ps

          echo "Resolving FlareSolverr via nslookup:"
          docker run --network job_network nicolaka/netshoot nslookup flaresolverr || echo "Failed to resolve FlareSolverr"

          echo "Current DNS configuration:"
          cat /etc/resolv.conf

      - name: Run Enhanced Indeed Scraper Test
        env:
          FLARESOLVERR_URL: http://host.docker.internal:8191/v1
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python -m app.scrapers.scraper_main --test-indeed --category=${{ github.event.inputs.category }}

      - name: List Generated Files
        if: always()
        run: |
          echo "Directory contents:"
          ls -la
          echo "Screenshots directory:"
          ls -la screenshots/ || echo "No screenshots found"

      - name: Upload Screenshots as Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: indeed-scraper-screenshots
          path: |
            screenshots/**/*.png
            *.png
          if-no-files-found: warn

      - name: Cleanup Docker Services
        if: always()
        run: |
          docker-compose down --remove-orphans
