name: Test Enhanced Indeed Scraper

on:
  workflow_dispatch:
    inputs:
      category:
        description: 'Job category to test'
        required: false
        default: 'python_developer'
        type: choice
        options:
          - python_developer
          - data_engineer
          - data_scientist

jobs:
  test-enhanced-indeed-scraper:
    runs-on: ubuntu-latest
    env:
      LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
      LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libnss3 \
            libxss1 \
            libatk-bridge2.0-0 \
            libgbm-dev \
            libgtk-3-0 \
            libxshmfence-dev \
            docker-compose

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.actions.txt
          pip install playwright httpx
          playwright install --with-deps

      - name: Start Docker services
        run: |
          docker-compose up -d
          # Wait for services to be fully up
          sleep 30
          # Verify running containers
          docker ps
          # Check logs of specific services if needed
          docker logs flaresolverr

      - name: Debug Environment
        run: |
          echo "Python version:"
          python --version
          echo "Playwright version:"
          pip show playwright
          echo "Docker Compose services:"
          docker-compose ps

      - name: Run Enhanced Indeed Scraper Test
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" python -m app.scrapers.scraper_main --test-indeed

      - name: List generated files
        if: always()
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Screenshots directory contents:"
          ls -la screenshots/ || echo "No screenshots directory"

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: indeed-scraper-screenshots
          path: |
            screenshots/**/*.png
            *.png
          if-no-files-found: warn

      - name: Cleanup Docker services
        if: always()
        run: |
          docker-compose down